name: Manual Build

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name : install ndk
      run: | 
        sudo curl --silent --show-error --location --fail --retry 3 \
          --output /tmp/$NDK_VERSION.zip \
          https://dl.google.com/android/repository/$NDK_VERSION-linux-x86_64.zip

        sudo echo "$NDK_SHA /tmp/$NDK_VERSION.zip" > /tmp/$NDK_VERSION.zip.sha1

        sha1sum -c /tmp/$NDK_VERSION.zip.sha1

        sudo rm -rf $ANDROID_SDK_ROOT/ndk-bundle
        sudo unzip -q /tmp/$NDK_VERSION.zip -d $ANDROID_SDK_ROOT
        sudo mv $ANDROID_SDK_ROOT/$NDK_VERSION $ANDROID_SDK_ROOT/ndk-bundle
        sudo chown -R root:root $ANDROID_SDK_ROOT/ndk-bundle
        sudo rm -f /tmp/$NDK_VERSION*

        if [[ -d $ANDROID_SDK_ROOT/ndk-bundle && \
          -n "$(ls -A $ANDROID_SDK_ROOT/ndk-bundle)" ]]; then
          echo "Android NDK installed"
        else
          echo "Android NDK did not install successfully"
          exit 1
        fi
      env:
        NDK_SHA: 500679655da3a86aecf67007e8ab230ea9b4dd7b
        NDK_VERSION: android-ndk-r18b
    - name: Build with Gradle
      run: ./gradlew build